### PR TITLE
Required/tasks 3

### PR DESCRIPTION
**Pull request by eduardourso**
TL;DR

Calculator task 3 of the Required Tasks in the Programming Project 1.

Problem

There weren't actions, buttons and logic to cover `sin`, `cos` and `π` operations. 

Solution
- Added buttons in the storyboard for the missing actions
- Created another Operation called EmptyOperation to deal with the π value return.

Test(s) added

NO.

Paired with

just me

### CODE REVIEW

**Comment by amlcurran** [comment]
Going to have to sort out the conflicts here :)

**Comment by eduardourso** [comment]
@amlcurran I think I didn't mention but this branch should be the last one to be merged. This comes after the [required/tasks-4-5](https://github.com/eduardourso/Calculator/pull/4)

**Comment by eduardourso** [comment]
@amlcurran conflicts sorted. 😄

**Comment by amlcurran** [comment]
Tiny PR 👍

**Pull request merged**
